//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioOnePack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioOnePack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analyze {
            get {
                object obj = ResourceManager.GetObject("analyze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burn {
            get {
                object obj = ResourceManager.GetObject("burn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap convert {
            get {
                object obj = ResourceManager.GetObject("convert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disc_info {
            get {
                object obj = ResourceManager.GetObject("disc_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap erasecd {
            get {
                object obj = ResourceManager.GetObject("erasecd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc inserted is not an Audio CD.
        /// </summary>
        internal static string IDS_ANALYZE_NOTAUDIOCD {
            get {
                return ResourceManager.GetString("IDS_ANALYZE_NOTAUDIOCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknow.
        /// </summary>
        internal static string IDS_ANALYZE_UNKNOWQUALITY {
            get {
                return ResourceManager.GetString("IDS_ANALYZE_UNKNOWQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0:C}&apos; file is in wrong format.
        /// </summary>
        internal static string IDS_ANALYZE_WRONGFILE {
            get {
                return ResourceManager.GetString("IDS_ANALYZE_WRONGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format.
        /// </summary>
        internal static string IDS_ANALYZE_WRONGFILE_CAPTION {
            get {
                return ResourceManager.GetString("IDS_ANALYZE_WRONGFILE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D}/{1:D} files analyzing is in progress.
        /// </summary>
        internal static string IDS_ANALYZEPROCESS_ANALYZE {
            get {
                return ResourceManager.GetString("IDS_ANALYZEPROCESS_ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file: {0:C}.
        /// </summary>
        internal static string IDS_ANALYZEPROCESS_CURRENTFILE {
            get {
                return ResourceManager.GetString("IDS_ANALYZEPROCESS_CURRENTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD burning....
        /// </summary>
        internal static string IDS_AUDIOBURN_BURN {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_BURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning is complete!.
        /// </summary>
        internal static string IDS_AUDIOBURN_COMPLETE {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating track #{0:D} of {1:D} tracks list.
        /// </summary>
        internal static string IDS_AUDIOBURN_CREATING {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files decoding....
        /// </summary>
        internal static string IDS_AUDIOBURN_DECODING {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_DECODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to delete &apos;{0:C}&apos; temporary directory. {1:C}.
        /// </summary>
        internal static string IDS_AUDIOBURN_ERRORDELTEMP {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_ERRORDELTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to create temporary files.
        /// </summary>
        internal static string IDS_AUDIOBURN_ERRORTMP {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_ERRORTMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_AUDIOBURN_ERRORTMP_CAPTION {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_ERRORTMP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string IDS_AUDIOBURN_WAIT {
            get {
                return ResourceManager.GetString("IDS_AUDIOBURN_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите музыкальные треки для записи Audio CD.
        /// </summary>
        internal static string IDS_AUDIOCD_EMPTYTEXT {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_EMPTYTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a blank CD!.
        /// </summary>
        internal static string IDS_AUDIOCD_INSERTBLANK {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_INSERTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add file &apos;{0:C}&apos;. You may add not more than 100 tracks..
        /// </summary>
        internal static string IDS_AUDIOCD_UNABLEADD {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_UNABLEADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string IDS_AUDIOCD_UNABLEADD_CAPTION {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_UNABLEADD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0:C}&apos; file is in wrong format.
        /// </summary>
        internal static string IDS_AUDIOCD_WRONGFORMAT {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_WRONGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format.
        /// </summary>
        internal static string IDS_AUDIOCD_WRONGFORMAT_CAPTION {
            get {
                return ResourceManager.GetString("IDS_AUDIOCD_WRONGFORMAT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Analyzer :: Audio One Pack.
        /// </summary>
        internal static string IDS_CAPTION_ANALYZE {
            get {
                return ResourceManager.GetString("IDS_CAPTION_ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Creator :: Audio One Pack.
        /// </summary>
        internal static string IDS_CAPTION_AUDIO {
            get {
                return ResourceManager.GetString("IDS_CAPTION_AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Converter :: Audio One Pack.
        /// </summary>
        internal static string IDS_CAPTION_CONVERT {
            get {
                return ResourceManager.GetString("IDS_CAPTION_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music CD Creator :: Audio One Pack.
        /// </summary>
        internal static string IDS_CAPTION_MUSIC {
            get {
                return ResourceManager.GetString("IDS_CAPTION_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Ripper :: Audio One Pack.
        /// </summary>
        internal static string IDS_CAPTION_RIP {
            get {
                return ResourceManager.GetString("IDS_CAPTION_RIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D}/{1:D} files converting is in progress.
        /// </summary>
        internal static string IDS_CONVERTPROCESS_CONVERT {
            get {
                return ResourceManager.GetString("IDS_CONVERTPROCESS_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file: {0:C}.
        /// </summary>
        internal static string IDS_CONVERTPROCESS_CURRENTFILE {
            get {
                return ResourceManager.GetString("IDS_CONVERTPROCESS_CURRENTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file {0:C}.
        /// </summary>
        internal static string IDS_CONVERTPROCESS_UNABLEDELETE {
            get {
                return ResourceManager.GetString("IDS_CONVERTPROCESS_UNABLEDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD or DVD device is not found.
        /// </summary>
        internal static string IDS_DEVICENOTFOUND {
            get {
                return ResourceManager.GetString("IDS_DEVICENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_DEVICENOTFOUND_CAPTION {
            get {
                return ResourceManager.GetString("IDS_DEVICENOTFOUND_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session {0:D}.
        /// </summary>
        internal static string IDS_DISKINFO_SESSION {
            get {
                return ResourceManager.GetString("IDS_DISKINFO_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: {0:D02}:{1:D02}  Finish: {2:D02}:{3:D02}  Length: {4:D02}:{5:D02},.
        /// </summary>
        internal static string IDS_DISKINFO_TRACK {
            get {
                return ResourceManager.GetString("IDS_DISKINFO_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0:F2} Mb.
        /// </summary>
        internal static string IDS_DISKINFO_TRACKSIZE {
            get {
                return ResourceManager.GetString("IDS_DISKINFO_TRACKSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the full mode is selected then all old data will be deleted.
        /// </summary>
        internal static string IDS_ERASECDRW_FULL {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disc is not rewritable and therefore cannot be erased. Please insert a rewritable disc..
        /// </summary>
        internal static string IDS_ERASECDRW_NOTERASE {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_NOTERASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disc is not rewritable.
        /// </summary>
        internal static string IDS_ERASECDRW_NOTERASE_CAPTION {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_NOTERASE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc erasing  was successfully completed.
        /// </summary>
        internal static string IDS_ERASECDRW_OK {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string IDS_ERASECDRW_OK_CAPTION {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_OK_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick mode does not physically erase data on the disk, but only deletes the area with the description of the disk contents..
        /// </summary>
        internal static string IDS_ERASECDRW_QUICK {
            get {
                return ResourceManager.GetString("IDS_ERASECDRW_QUICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string IDS_ISRUN_CAPTION {
            get {
                return ResourceManager.GetString("IDS_ISRUN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio One Pack software is already running!.
        /// </summary>
        internal static string IDS_ISRUN_WARNING {
            get {
                return ResourceManager.GetString("IDS_ISRUN_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Analyzer.
        /// </summary>
        internal static string IDS_LICENSE_ANALYZE {
            get {
                return ResourceManager.GetString("IDS_LICENSE_ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Creator.
        /// </summary>
        internal static string IDS_LICENSE_AUDIO {
            get {
                return ResourceManager.GetString("IDS_LICENSE_AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Converter.
        /// </summary>
        internal static string IDS_LICENSE_CONVERT {
            get {
                return ResourceManager.GetString("IDS_LICENSE_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string IDS_LICENSE_FULL {
            get {
                return ResourceManager.GetString("IDS_LICENSE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music CD Creator.
        /// </summary>
        internal static string IDS_LICENSE_MUSIC {
            get {
                return ResourceManager.GetString("IDS_LICENSE_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Ripper.
        /// </summary>
        internal static string IDS_LICENSE_RIP {
            get {
                return ResourceManager.GetString("IDS_LICENSE_RIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files to the disk structure.
        /// </summary>
        internal static string IDS_MUSICBURN_ADDINGFILES {
            get {
                return ResourceManager.GetString("IDS_MUSICBURN_ADDINGFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning is complete!.
        /// </summary>
        internal static string IDS_MUSICBURN_COMPLETE {
            get {
                return ResourceManager.GetString("IDS_MUSICBURN_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete?.
        /// </summary>
        internal static string IDS_MUSICCD_DELNODE {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_DELNODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string IDS_MUSICCD_DELNODE_CAPTION {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_DELNODE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space to burn this compilation onto this disc! Please, remove the extra files.
        /// </summary>
        internal static string IDS_MUSICCD_ERRORCDSIZE {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_ERRORCDSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with this name already exists! Please, change the name..
        /// </summary>
        internal static string IDS_MUSICCD_EXISTDIR {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_EXISTDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a blank CD!.
        /// </summary>
        internal static string IDS_MUSICCD_INSERTBLANK {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_INSERTBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string IDS_MUSICCD_NEWFOLDER {
            get {
                return ResourceManager.GetString("IDS_MUSICCD_NEWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.audioonepack.com/order.xhtml.
        /// </summary>
        internal static string IDS_ORDER_LINK {
            get {
                return ResourceManager.GetString("IDS_ORDER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диск не пустой. Выполнить быстрое стирание диска?.
        /// </summary>
        internal static string IDS_QUICKERASE {
            get {
                return ResourceManager.GetString("IDS_QUICKERASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диск не пустой.
        /// </summary>
        internal static string IDS_QUICKERASE_CAPTION {
            get {
                return ResourceManager.GetString("IDS_QUICKERASE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key you entered is not valid!.
        /// </summary>
        internal static string IDS_REGISTRATION_CANCEL {
            get {
                return ResourceManager.GetString("IDS_REGISTRATION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. {0:S} has been registered!.
        /// </summary>
        internal static string IDS_REGISTRATION_OK {
            get {
                return ResourceManager.GetString("IDS_REGISTRATION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist {0:D02}.
        /// </summary>
        internal static string IDS_RIPCD_ARTIST {
            get {
                return ResourceManager.GetString("IDS_RIPCD_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста вставьте Audio CD.
        /// </summary>
        internal static string IDS_RIPCD_EMPTYTEXT {
            get {
                return ResourceManager.GetString("IDS_RIPCD_EMPTYTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to get information about this CD album from a CDDB server?.
        /// </summary>
        internal static string IDS_RIPCD_GETCDDB {
            get {
                return ResourceManager.GetString("IDS_RIPCD_GETCDDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query for a CDDB server information is in process.
        /// </summary>
        internal static string IDS_RIPCD_GETCDDB_CAPTION {
            get {
                return ResourceManager.GetString("IDS_RIPCD_GETCDDB_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string IDS_RIPCD_MENU_SELECT {
            get {
                return ResourceManager.GetString("IDS_RIPCD_MENU_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string IDS_RIPCD_MENU_SELECTALL {
            get {
                return ResourceManager.GetString("IDS_RIPCD_MENU_SELECTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        internal static string IDS_RIPCD_MENU_UNSELECT {
            get {
                return ResourceManager.GetString("IDS_RIPCD_MENU_UNSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        internal static string IDS_RIPCD_MENU_UNSELECTALL {
            get {
                return ResourceManager.GetString("IDS_RIPCD_MENU_UNSELECTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0:D02}.
        /// </summary>
        internal static string IDS_RIPCD_TRACK {
            get {
                return ResourceManager.GetString("IDS_RIPCD_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Artist.
        /// </summary>
        internal static string IDS_RIPCD_UNKNOWARTIST {
            get {
                return ResourceManager.GetString("IDS_RIPCD_UNKNOWARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Title.
        /// </summary>
        internal static string IDS_RIPCD_UNKNOWTITLE {
            get {
                return ResourceManager.GetString("IDS_RIPCD_UNKNOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve CD Information.
        /// </summary>
        internal static string IDS_RIPFREEDB_ERRORCDDB {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_ERRORCDDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query did not succeed: .
        /// </summary>
        internal static string IDS_RIPFREEDB_ERRORQUERY {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_ERRORQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Drive is not ready or cannot read cd. Details:.
        /// </summary>
        internal static string IDS_RIPFREEDB_ERRORREAD {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_ERRORREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve cd entry. Code:.
        /// </summary>
        internal static string IDS_RIPFREEDB_ERRORRESULT {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_ERRORRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access CD Drive:.
        /// </summary>
        internal static string IDS_RIPFREEDB_NOTACCESS {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_NOTACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Drive is not ready. Please check drive:.
        /// </summary>
        internal static string IDS_RIPFREEDB_NOTREADY {
            get {
                return ResourceManager.GetString("IDS_RIPFREEDB_NOTREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D}/{1:D} files encoding is in progress.
        /// </summary>
        internal static string IDS_RIPPROCESS_ENCODE {
            get {
                return ResourceManager.GetString("IDS_RIPPROCESS_ENCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to create temporary files.
        /// </summary>
        internal static string IDS_RIPPROCESS_ERRORTMP {
            get {
                return ResourceManager.GetString("IDS_RIPPROCESS_ERRORTMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_RIPPROCESS_ERRORTMP_CAPTION {
            get {
                return ResourceManager.GetString("IDS_RIPPROCESS_ERRORTMP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of Audio Track #{0:D} ({1:D}/{2:D}).
        /// </summary>
        internal static string IDS_RIPPROCESS_INFO {
            get {
                return ResourceManager.GetString("IDS_RIPPROCESS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge of files is in process.
        /// </summary>
        internal static string IDS_RIPPROCESS_MERGE {
            get {
                return ResourceManager.GetString("IDS_RIPPROCESS_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Analyzer.
        /// </summary>
        internal static string IDS_TABANALYZER {
            get {
                return ResourceManager.GetString("IDS_TABANALYZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Creator.
        /// </summary>
        internal static string IDS_TABAUDIO {
            get {
                return ResourceManager.GetString("IDS_TABAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Converter.
        /// </summary>
        internal static string IDS_TABCONVERTER {
            get {
                return ResourceManager.GetString("IDS_TABCONVERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music CD Creator.
        /// </summary>
        internal static string IDS_TABMUSIC {
            get {
                return ResourceManager.GetString("IDS_TABMUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio CD Ripper.
        /// </summary>
        internal static string IDS_TABRIP {
            get {
                return ResourceManager.GetString("IDS_TABRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version allows to analyze only the first three tracks!.
        /// </summary>
        internal static string IDS_TRIAL_ANALYZE {
            get {
                return ResourceManager.GetString("IDS_TRIAL_ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version allows to burn only the first five tracks.
        /// </summary>
        internal static string IDS_TRIAL_AUDIO {
            get {
                return ResourceManager.GetString("IDS_TRIAL_AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version.
        /// </summary>
        internal static string IDS_TRIAL_CAPTION {
            get {
                return ResourceManager.GetString("IDS_TRIAL_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version allows to convert only 30% of original track.
        /// </summary>
        internal static string IDS_TRIAL_CONVERT {
            get {
                return ResourceManager.GetString("IDS_TRIAL_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version allows to burn 100 Mb maximum.
        /// </summary>
        internal static string IDS_TRIAL_MUSIC {
            get {
                return ResourceManager.GetString("IDS_TRIAL_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered version allows to rip only 30% of original track.
        /// </summary>
        internal static string IDS_TRIAL_RIP {
            get {
                return ResourceManager.GetString("IDS_TRIAL_RIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ie2 {
            get {
                object obj = ResourceManager.GetObject("ie2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mp3 {
            get {
                object obj = ResourceManager.GetObject("mp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prev {
            get {
                object obj = ResourceManager.GetObject("prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quit {
            get {
                object obj = ResourceManager.GetObject("quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_small {
            get {
                object obj = ResourceManager.GetObject("refresh_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rip {
            get {
                object obj = ResourceManager.GetObject("rip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_add_dir {
            get {
                object obj = ResourceManager.GetObject("tree_add_dir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_add_dirfile {
            get {
                object obj = ResourceManager.GetObject("tree_add_dirfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_add_file {
            get {
                object obj = ResourceManager.GetObject("tree_add_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_delete {
            get {
                object obj = ResourceManager.GetObject("tree_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_down {
            get {
                object obj = ResourceManager.GetObject("tree_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_left {
            get {
                object obj = ResourceManager.GetObject("tree_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_right {
            get {
                object obj = ResourceManager.GetObject("tree_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_up {
            get {
                object obj = ResourceManager.GetObject("tree_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
